### PR TITLE
fix loss of stereochemistry information in export to SMILES string

### PR DESCRIPTION
**Pull request by Veikun**

### CODE REVIEW

**Comment by Veikun** [comment]
[PR#55](https://github.com/epam/ketcher/pull/55) from October 2020 introduced the attributes stereoLabel and stereoParity to the internal Atom type. 

The getSMILES() function we use to export to the MM kernel was still using ~2018 code to re-compute stereocenters every time the export to SMILES was called. This code was no longer compatible with the changes from PR#55, and also unnecessary because this stereochemical information is now pre-calculated and store in the new fields in Atom.

**Comment by jhyman2** [comment]
@Veikun or @thomasklau or @sdurham or @bencsmith should make this repo private so those outside ECL cannot see...good luck 😄 

Hope you guys are all doing well ❤️

**Comment by sdurham** [comment]
Hi @jhyman2 that is intentional 😄 

I think we have to because it is a forked public repo, and some other reasons.
Will try to keep the super secret sauce out of it.

**Comment by Veikun** [comment]
Revision to previous comment:

The stereoParity assigned to each atom is a little buggy for SMILES output. To resolve this, I fixed the StereoCenters() code (there was inconsistent indentation and an un-closed if statement which was causing the stereocenter detection code not to run).

**Review by amassaro-ecl — APPROVED** [review]

**Pull request merged**
